<?php
 $url = "http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml";


 $invalidurl = false;
 if(@simplexml_load_file($url)){
  $xml = simplexml_load_file($url);
 }else{
  $invalidurl = true;
  echo "<h2>Invalid feed URL.</h2>";
 }
?>
<table>
    <tbody>
    <tr>
    <th>CurrencyName</th>
    <th>Sell</th>
    </tr>
  <?php foreach ($xml->Cube->Cube->Cube as $Exrate) : ?>
        <tr>
            <td> <?php echo $Exrate["currency"]; ?> </td>
            <td> <?php echo $Exrate["rate"]; ?> </td>
        </tr>
		<?php endforeach; ?>
	</tbody>
</table>